### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by brunns** [noirbizarre/setuptools-meta#1]
This looks fantastic, but it's not installing for us:

```
Couldn't find index page for 'setuptools-meta' (maybe misspelled?)
No local packages or working download links found for setuptools-meta
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    "git_branch": subprocess.check_output(["git", "symbolic-ref", "-q", "--short", "HEAD"]),
  File "/Users/simonbrunning/Library/Python/2.7/lib/python/site-packages/setuptools/__init__.py", line 130, in setup
    _install_setup_requires(attrs)
  File "/Users/simonbrunning/Library/Python/2.7/lib/python/site-packages/setuptools/__init__.py", line 125, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/Users/simonbrunning/Library/Python/2.7/lib/python/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
    replace_conflicting=True,
  File "/Users/simonbrunning/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 773, in resolve
    replace_conflicting=replace_conflicting
  File "/Users/simonbrunning/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 1056, in best_match
    return self.obtain(req, installer)
  File "/Users/simonbrunning/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 1068, in obtain
    return installer(requirement)
  File "/Users/simonbrunning/Library/Python/2.7/lib/python/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Users/simonbrunning/Library/Python/2.7/lib/python/site-packages/setuptools/command/easy_install.py", line 670, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-meta')
make: *** [install-dashboard-generator] Error 1
```

I'm assuming that this is because setuptools-meta hasn't been uploaded to PyPi yet. Are you planning to do that? Happy to help out if that's useful.

**Comment by N-Coder** [comment]
You can add the following config to your `setup(**kwargs)` call to fix this in the meantime:
```
        dependency_links=[
            "git+https://github.com/noirbizarre/setuptools-meta.git#egg=setuptools-meta"
        ],
```

**Comment by N-Coder** [comment]
@noirbizarre would it be okay if I published this to PyPi to make it easily available? I don't see a reason for forking your repo and would also be perfectly fine with leaving the ownership on PyPi to you, as long as someone puts it there. ;)
